"""
Export service for generating Excel, Word, PDF, and other formats.
"""
from typing import Dict, Any
from io import BytesIO
from datetime import datetime
import json
from app.utils.logger import logger


class ExportService:
    """Service for exporting execution data."""
    
    @staticmethod
    def to_json(data: Dict[str, Any], pretty: bool = True) -> str:
        """Export data to JSON format."""
        indent = 2 if pretty else None
        return json.dumps(data, indent=indent, default=str)

    @staticmethod
    def to_markdown(execution: Dict[str, Any], tasks: list = None) -> str:
        """Export execution result to Markdown format."""
        md = []
        md.append(f"# Execution Report\n")
        md.append(f"**Execution ID:** `{execution.get('id', 'N/A')}`\n")
        md.append(f"**Status:** {execution.get('status', 'N/A')}\n")
        md.append(f"**Created:** {execution.get('created_at', 'N/A')}\n")
        
        if execution.get('started_at'):
            md.append(f"**Started:** {execution.get('started_at')}\n")
        if execution.get('completed_at'):
            md.append(f"**Completed:** {execution.get('completed_at')}\n")
        
        md.append(f"\n## Statistics\n")
        md.append(f"- **Tokens Used:** {execution.get('tokens_used', 0):,}\n")
        md.append(f"- **Estimated Cost:** ${float(execution.get('estimated_cost', 0)):.4f}\n")
        
        if execution.get('input_data'):
            md.append(f"\n## Input Data\n")
            md.append(f"```json\n{json.dumps(execution.get('input_data'), indent=2)}\n```\n")
        
        if execution.get('result'):
            md.append(f"\n## Result\n")
            result = execution.get('result')
            if isinstance(result, dict):
                md.append(f"```json\n{json.dumps(result, indent=2)}\n```\n")
            else:
                md.append(f"{result}\n")
        
        if execution.get('error_message'):
            md.append(f"\n## Error\n")
            md.append(f"```\n{execution.get('error_message')}\n```\n")
        
        md.append(f"\n---\n")
        md.append(f"*Generated by CrewAI Manager at {datetime.utcnow().isoformat()}*\n")
        
        return "".join(md)

    @staticmethod
    def to_html(execution: Dict[str, Any]) -> str:
        """Export execution to HTML format."""
        html = f"""<!DOCTYPE html>
<html>
<head>
    <title>Execution Report - {execution.get('id', 'N/A')}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 900px; margin: 0 auto; padding: 20px; background: #f5f5f5; }}
        .container {{ background: white; padding: 30px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }}
        h1 {{ color: #1e40af; border-bottom: 2px solid #1e40af; padding-bottom: 10px; }}
        .status {{ display: inline-block; padding: 6px 16px; border-radius: 20px; font-size: 14px; font-weight: 600; }}
        .status-completed {{ background: #d1fae5; color: #065f46; }}
        .status-failed {{ background: #fee2e2; color: #991b1b; }}
        .status-running {{ background: #dbeafe; color: #1e40af; }}
        .status-pending {{ background: #f3f4f6; color: #374151; }}
        .stat-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 15px; margin: 20px 0; }}
        .stat {{ background: #f9fafb; padding: 15px; border-radius: 8px; }}
        .stat-label {{ font-size: 12px; color: #6b7280; text-transform: uppercase; }}
        .stat-value {{ font-size: 20px; font-weight: 600; color: #111827; margin-top: 5px; }}
        pre {{ background: #1f2937; color: #10b981; padding: 20px; border-radius: 8px; overflow-x: auto; }}
        .error {{ background: #fee2e2; color: #991b1b; padding: 15px; border-radius: 8px; }}
        .section {{ margin-top: 30px; }}
        .section h2 {{ color: #374151; font-size: 18px; margin-bottom: 15px; }}
    </style>
</head>
<body>
    <div class="container">
        <h1>Execution Report</h1>
        <p><strong>ID:</strong> <code>{execution.get('id', 'N/A')}</code></p>
        <p><strong>Status:</strong> <span class="status status-{execution.get('status', 'pending')}">{execution.get('status', 'N/A').upper()}</span></p>
        
        <div class="stat-grid">
            <div class="stat">
                <div class="stat-label">Created</div>
                <div class="stat-value">{execution.get('created_at', 'N/A')}</div>
            </div>
            <div class="stat">
                <div class="stat-label">Tokens Used</div>
                <div class="stat-value">{execution.get('tokens_used', 0):,}</div>
            </div>
            <div class="stat">
                <div class="stat-label">Estimated Cost</div>
                <div class="stat-value">${float(execution.get('estimated_cost', 0)):.4f}</div>
            </div>
        </div>
        
        {"<div class='section'><h2>Result</h2><pre>" + json.dumps(execution.get('result'), indent=2) + "</pre></div>" if execution.get('result') else ""}
        
        {"<div class='section'><h2>Error</h2><div class='error'>" + execution.get('error_message', '') + "</div></div>" if execution.get('error_message') else ""}
        
        <p style="margin-top: 30px; color: #9ca3af; font-size: 12px;">Generated by CrewAI Manager at {datetime.utcnow().isoformat()}</p>
    </div>
</body>
</html>"""
        return html

    @staticmethod
    def export_to_excel(data: Dict[str, Any]) -> BytesIO:
        """Export execution data to Excel."""
        try:
            import pandas as pd
            
            buffer = BytesIO()
            
            with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
                info_df = pd.DataFrame([{
                    'Execution ID': data.get('Execution ID', data.get('id', '')),
                    'Status': data.get('Status', data.get('status', '')),
                    'Result': str(data.get('Result', data.get('result', ''))),
                    'Created At': data.get('Created At', data.get('created_at', '')),
                    'Started At': data.get('Started At', data.get('started_at', 'Not started')),
                    'Completed At': data.get('Completed At', data.get('completed_at', 'Not completed')),
                    'Tokens Used': data.get('Tokens Used', data.get('tokens_used', 0)),
                    'Estimated Cost': data.get('Estimated Cost', data.get('estimated_cost', 0)),
                }])
                info_df.to_excel(writer, sheet_name='Execution Info', index=False)
                
                if data.get('Logs') or data.get('logs'):
                    logs_df = pd.DataFrame([{'Logs': data.get('Logs', data.get('logs', ''))}])
                    logs_df.to_excel(writer, sheet_name='Logs', index=False)
            
            buffer.seek(0)
            logger.info("Excel export completed successfully")
            return buffer
            
        except ImportError:
            logger.error("pandas or openpyxl not installed")
            raise ValueError("Excel export requires pandas and openpyxl")
        except Exception as e:
            logger.error(f"Excel export failed: {str(e)}")
            raise

    @staticmethod
    def export_to_word(data: Dict[str, Any]) -> BytesIO:
        """Export execution data to Word."""
        try:
            from docx import Document
            from docx.shared import Pt
            from docx.enum.text import WD_ALIGN_PARAGRAPH
            
            buffer = BytesIO()
            doc = Document()
            
            title = doc.add_heading('Execution Report', 0)
            title.alignment = WD_ALIGN_PARAGRAPH.CENTER
            
            doc.add_heading('Execution Information', level=1)
            
            info_table = doc.add_table(rows=8, cols=2)
            info_table.style = 'Table Grid'
            
            rows_data = [
                ('Execution ID', data.get('Execution ID', data.get('id', ''))),
                ('Status', data.get('Status', data.get('status', ''))),
                ('Created At', data.get('Created At', data.get('created_at', ''))),
                ('Started At', data.get('Started At', data.get('started_at', 'Not started'))),
                ('Completed At', data.get('Completed At', data.get('completed_at', 'Not completed'))),
                ('Tokens Used', str(data.get('Tokens Used', data.get('tokens_used', 0)))),
                ('Estimated Cost', f"${data.get('Estimated Cost', data.get('estimated_cost', 0))}"),
                ('Result', str(data.get('Result', data.get('result', '')))[:500]),
            ]
            
            for i, (label, value) in enumerate(rows_data):
                info_table.rows[i].cells[0].text = label
                info_table.rows[i].cells[1].text = str(value)
            
            if data.get('Logs') or data.get('logs'):
                doc.add_page_break()
                doc.add_heading('Execution Logs', level=1)
                doc.add_paragraph(data.get('Logs', data.get('logs', 'No logs available')))
            
            doc.save(buffer)
            buffer.seek(0)
            logger.info("Word export completed successfully")
            return buffer
            
        except ImportError:
            logger.error("python-docx not installed")
            raise ValueError("Word export requires python-docx")
        except Exception as e:
            logger.error(f"Word export failed: {str(e)}")
            raise

    @staticmethod
    def export_to_pdf(data: Dict[str, Any]) -> BytesIO:
        """Export execution data to PDF."""
        try:
            from reportlab.lib.pagesizes import letter
            from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
            from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
            from reportlab.lib import colors
            from reportlab.lib.units import inch
            
            buffer = BytesIO()
            doc = SimpleDocTemplate(buffer, pagesize=letter)
            styles = getSampleStyleSheet()
            story = []
            
            title_style = ParagraphStyle(
                'CustomTitle',
                parent=styles['Heading1'],
                fontSize=24,
                textColor=colors.HexColor('#1e40af'),
                spaceAfter=30,
                alignment=1,
            )
            story.append(Paragraph('Execution Report', title_style))
            story.append(Spacer(1, 0.5*inch))
            
            story.append(Paragraph('Execution Information', styles['Heading2']))
            story.append(Spacer(1, 0.2*inch))
            
            table_data = [
                ['Field', 'Value'],
                ['Execution ID', str(data.get('Execution ID', data.get('id', '')))[:50]],
                ['Status', data.get('Status', data.get('status', ''))],
                ['Created At', str(data.get('Created At', data.get('created_at', '')))],
                ['Tokens Used', str(data.get('Tokens Used', data.get('tokens_used', 0)))],
                ['Estimated Cost', f"${data.get('Estimated Cost', data.get('estimated_cost', 0))}"],
            ]
            
            table = Table(table_data, colWidths=[2*inch, 4*inch])
            table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e40af')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 11),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('GRID', (0, 0), (-1, -1), 1, colors.black),
                ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
                ('FONTSIZE', (0, 1), (-1, -1), 10),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f3f4f6')]),
            ]))
            
            story.append(table)
            
            doc.build(story)
            buffer.seek(0)
            logger.info("PDF export completed successfully")
            return buffer
            
        except ImportError:
            logger.error("reportlab not installed")
            raise ValueError("PDF export requires reportlab")
        except Exception as e:
            logger.error(f"PDF export failed: {str(e)}")
            raise


# Singleton instance
export_service = ExportService()
