"""
Export service for generating different output formats.
"""
import json
from typing import Any, Dict
from datetime import datetime
from io import BytesIO
from app.utils.logger import logger


class ExportService:
    """Service for exporting execution results to various formats."""

    @staticmethod
    def to_json(data: Dict[str, Any], pretty: bool = True) -> str:
        """
        Export data to JSON format.
        
        Args:
            data: Data to export
            pretty: Whether to format with indentation
            
        Returns:
            JSON string
        """
        indent = 2 if pretty else None
        return json.dumps(data, indent=indent, default=str)

    @staticmethod
    def to_markdown(execution: Dict[str, Any], tasks: list = None) -> str:
        """
        Export execution result to Markdown format.
        
        Args:
            execution: Execution data
            tasks: Optional list of tasks
            
        Returns:
            Markdown string
        """
        md = []
        
        # Header
        md.append(f"# Execution Report")
        md.append(f"\n**Execution ID:** `{execution.get('id', 'N/A')}`")
        md.append(f"\n**Status:** {execution.get('status', 'N/A')}")
        md.append(f"\n**Created:** {execution.get('created_at', 'N/A')}")
        
        if execution.get('started_at'):
            md.append(f"\n**Started:** {execution.get('started_at')}")
        if execution.get('completed_at'):
            md.append(f"\n**Completed:** {execution.get('completed_at')}")
        
        # Stats
        md.append(f"\n\n## Statistics")
        md.append(f"\n- **Tokens Used:** {execution.get('tokens_used', 0):,}")
        md.append(f"\n- **Estimated Cost:** ${float(execution.get('estimated_cost', 0)):.4f}")
        
        # Input
        if execution.get('input_data'):
            md.append(f"\n\n## Input Data")
            md.append(f"\n```json\n{json.dumps(execution.get('input_data'), indent=2)}\n```")
        
        # Result
        if execution.get('result'):
            md.append(f"\n\n## Result")
            result = execution.get('result')
            if isinstance(result, dict):
                md.append(f"\n```json\n{json.dumps(result, indent=2)}\n```")
            else:
                md.append(f"\n{result}")
        
        # Error
        if execution.get('error_message'):
            md.append(f"\n\n## Error")
            md.append(f"\n```\n{execution.get('error_message')}\n```")
        
        # Tasks
        if tasks:
            md.append(f"\n\n## Tasks")
            for i, task in enumerate(tasks, 1):
                md.append(f"\n### {i}. {task.get('name', 'Task')}")
                md.append(f"\n- **Status:** {task.get('status', 'N/A')}")
                if task.get('output'):
                    md.append(f"\n- **Output:** {task.get('output')}")
        
        # Footer
        md.append(f"\n\n---")
        md.append(f"\n*Generated by CrewAI Manager at {datetime.utcnow().isoformat()}*")
        
        return "\n".join(md)

    @staticmethod
    def to_csv(executions: list) -> str:
        """
        Export executions list to CSV format.
        
        Args:
            executions: List of execution data
            
        Returns:
            CSV string
        """
        import csv
        from io import StringIO
        
        output = StringIO()
        writer = csv.writer(output)
        
        # Header
        writer.writerow([
            'ID', 'Project ID', 'Status', 'Tokens Used', 
            'Estimated Cost', 'Created At', 'Completed At'
        ])
        
        # Data
        for exec in executions:
            writer.writerow([
                exec.get('id', ''),
                exec.get('project_id', ''),
                exec.get('status', ''),
                exec.get('tokens_used', 0),
                exec.get('estimated_cost', 0),
                exec.get('created_at', ''),
                exec.get('completed_at', ''),
            ])
        
        return output.getvalue()

    @staticmethod
    def to_excel(executions: list) -> BytesIO:
        """
        Export executions to Excel format.
        
        Args:
            executions: List of execution data
            
        Returns:
            BytesIO object containing Excel file
        """
        try:
            import pandas as pd
            
            df = pd.DataFrame([{
                'ID': exec.get('id', ''),
                'Project ID': exec.get('project_id', ''),
                'Status': exec.get('status', ''),
                'Tokens Used': exec.get('tokens_used', 0),
                'Estimated Cost': float(exec.get('estimated_cost', 0)),
                'Created At': exec.get('created_at', ''),
                'Completed At': exec.get('completed_at', ''),
            } for exec in executions])
            
            output = BytesIO()
            df.to_excel(output, index=False, sheet_name='Executions')
            output.seek(0)
            
            return output
            
        except ImportError:
            logger.error("pandas or openpyxl not installed for Excel export")
            raise ValueError("Excel export not available")

    @staticmethod
    def to_html(execution: Dict[str, Any]) -> str:
        """
        Export execution to HTML format.
        
        Args:
            execution: Execution data
            
        Returns:
            HTML string
        """
        html = f"""
<!DOCTYPE html>
<html>
<head>
    <title>Execution Report - {execution.get('id', 'N/A')}</title>
    <style>
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #1f2937; }}
        .status {{ display: inline-block; padding: 4px 12px; border-radius: 9999px; font-size: 14px; font-weight: 500; }}
        .status-completed {{ background: #d1fae5; color: #065f46; }}
        .status-failed {{ background: #fee2e2; color: #991b1b; }}
        .status-running {{ background: #dbeafe; color: #1e40af; }}
        .stat {{ background: #f3f4f6; padding: 16px; border-radius: 8px; margin: 8px 0; }}
        pre {{ background: #1f2937; color: #10b981; padding: 16px; border-radius: 8px; overflow-x: auto; }}
        .error {{ background: #fee2e2; color: #991b1b; padding: 16px; border-radius: 8px; }}
    </style>
</head>
<body>
    <h1>Execution Report</h1>
    <p><strong>ID:</strong> <code>{execution.get('id', 'N/A')}</code></p>
    <p><strong>Status:</strong> <span class="status status-{execution.get('status', 'pending')}">{execution.get('status', 'N/A')}</span></p>
    <p><strong>Created:</strong> {execution.get('created_at', 'N/A')}</p>
    
    <h2>Statistics</h2>
    <div class="stat">
        <strong>Tokens Used:</strong> {execution.get('tokens_used', 0):,}<br>
        <strong>Estimated Cost:</strong> ${float(execution.get('estimated_cost', 0)):.4f}
    </div>
    
    {"<h2>Result</h2><pre>" + json.dumps(execution.get('result'), indent=2) + "</pre>" if execution.get('result') else ""}
    
    {"<h2>Error</h2><div class='error'>" + execution.get('error_message', '') + "</div>" if execution.get('error_message') else ""}
    
    <hr>
    <p><em>Generated by CrewAI Manager at {datetime.utcnow().isoformat()}</em></p>
</body>
</html>
"""
        return html


# Singleton instance
export_service = ExportService()
